### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by mo9a7i** [ahmedrowaihi/listen-up#2]
Great project boss 👍🏽!

- Would you like to setup CI/CD for auto release to NPM after a push?
- Do you wanna use [Winston](https://www.npmjs.com/package/winston) for logging?
- What about [changeset](https://github.com/changesets/changesets) for versioning and changelog maintenance.

let me know if you want any of these

**Comment by ahmedrowaihi** [comment]
Yw boss!
 - I will be adding CI/CD soon
 - [Winston](https://www.npmjs.com/package/winston) ? YES THAT WOULD BE AWESOME
 - I haven't used [changeset](https://github.com/changesets/changesets), I use [release-it](https://www.npmjs.com/package/release-it), what do you think ?
 
 Glad that you are here :'D
